### ISSUE TITLE
Not working Inkdrop update: 5.6.0

### ISSUE THREAD

**Issue by maniac-en** [sotakal/dont-need-status#1]
Hey

The latest update (as of now) for Inkdrop which is v5.6.0 shows the `status` in both side-bar and top-panel above note. Though the strange behavior I notice is that status options are expanding under the top-panel when clicked but not under the side-bar. Don't know if that helps but would love to hide the `status` option as it was hidden earlier.

Thanks!

**Comment by maniac-en** [comment]
Is this being maintained? @sotakal

**Comment by sotakal** [comment]
Sorry, no. I stopped using Inkdrop a while back.
